config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :employees, :vacancies do
    resources :skills
  end

  root 'welcome#index'

end

app/models/concerns/has_skills.rb
module HasSkills
  def self.included(base)
    base.class_eval do
      has_many :skill_links, as: :skillable
      has_many :skills, through: :skill_links

      accepts_nested_attributes_for :skill_links
    end
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include HasSkills

  validates :name, :contact, presence: true
  validates :name, name: true
  validates :contact, email: true

  default_scope {order(salary: :asc)}
  scope :active, -> {where(status: true)}
end

app/controllers/api/v1/employees_controller.rb
class Api::V1::EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :update, :destroy]
  include Gotskills
  include Gotaliens
  respond_to :json

  def index
    @employees = Employee.includes(:skills)
    respond_with @employees
  end

  def show
    got_skills @employee
    got_aliens @employee.skills, Vacancy.active.includes(:skills).order(salary: :desc)
    respond_with @employee
  end

  def new
    @employee = Employee.new
    @skill = Skill.new
  end

  def edit
    @employee = Employee.includes(:skills).find(params[:id])
    @skill = Skill.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.status ||= false
    @employee.salary = @employee.salary || 0
#    respond_with :api, :v1, Lead.create(lead_params)

    if @employee.skills.size == 0
      redirect_to :back, notice: 'Skills count cannot be zero'
    else
      respond_to do |format|
        if @employee.save
          format.html{ redirect_to @employee, notice: 'Employee created OK'}
          format.json{ render :show }
        else
          format.html{ render :new}
        end
      end
    end
  end

  def update
    @employee.skill_links.build.build_skill
    #    respond_with lead.update(lead_params)

    respond_to do |format|
      if @employee.update(employee_params)
        format.html{ redirect_to @employee, notice: 'Employee edited OK'}
      else
        format.html{ render :edit, notice: 'Employee not edited'}
      end
    end
  end

  def destroy
    @employee.destroy
#    respond_with lead.destroy
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :contact, :status, :salary, skill_ids:[])
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :update, :destroy]
  include Gotskills
  include Gotaliens

  respond_to :html, :json

  def index
    @employees = Employee.includes(:skills)
    respond_with(@employees)
  end

  def show
    got_skills @employee
    # with default_scope
    # got_aliens @employee.skills, Vacancy.active.includes(:skills)
    # w/o default_scope
    got_aliens @employee.skills, Vacancy.active.includes(:skills).order(salary: :desc)
  end

  def new
    @employee = Employee.new
    @skill = Skill.new
  end

  def edit
    @employee = Employee.includes(:skills).find(params[:id])
    @skill = Skill.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.status ||= false
    @employee.salary = @employee.salary || 0

    if @employee.skills.size == 0
      redirect_to :back, notice: 'Skills count cannot be zero'
    else
      respond_to do |format|
        if @employee.save
          format.html{ redirect_to @employee, notice: 'Employee created OK'}
          format.json{ render :show }
        else
          format.html{ render :new}
        end
      end
    end
  end

  def update
    @employee.skill_links.build.build_skill

    respond_to do |format|
      if @employee.update(employee_params)
        format.html{ redirect_to @employee, notice: 'Employee edited OK'}
      else
        format.html{ render :edit, notice: 'Employee not edited'}
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html{ redirect_to employees_path, notice: 'Employee killed' }
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :contact, :status, :salary, skill_ids:[])
  end

end

app/views/employees/_employee.html.erb
<div class="block">
  <h3><%= employee.name %></h3>
  <b>Salary:</b><i><%= employee.salary %></i>
  <br/>
  <% if employee.skills %>
    <small>
      <% employee.skills.each do |s| %>
          <%= s.name %>
      <% end %>
    </small>
  <% end %>

  <div class="buttons">
    <%= link_to 'show', employee %>
    <%= link_to 'edit', edit_employee_path(employee) %>
  </div>
</div>

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
    <% if @employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employee.errors.count, 'error')%> prohibited this emp from being saved</h2>
          <ul>
            <%= @employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, required: true, autofocus: true%>
    </div>
    <div class="field">
      <%= f.label :contact %>
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :salary %>
      <%= f.text_field :salary %>
    </div>
    <div class="field">
      <%= f.label :status %>
      <%= f.check_box :status %>
    </div>
    <div class="field" id="allskills">
      <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name %>
    </div>
    <div class="actions">
      <%= f.submit 'OK'%>
    </div>
<% end %>

app/views/employees/edit.html.erb
<% title @employee.name %>
<% menu 'back', employees_path %>

<%= render 'form' %>

<div class="center">
  <%= link_to 'create new skill', new_skill_path, id: 'add_skill', remote: true %>
</div>

app/views/employees/index.html.erb
<% title 'All employees' %>
<% menu 'add new', new_employee_path %>

<h1>Our employees</h1>

<%= render partial: 'employee', collection: @employees %>

app/views/employees/new.html.erb
<% title 'New Employee' %>
<% menu 'cancel', employees_path %>

<%= render 'form' %>

<div class="center">
  <%= link_to 'create new skill', new_skill_path, id: 'add_skill', remote: true %>
</div>

app/views/employees/show.html.erb
<% title @employee.name %>
<% menu 'edit', edit_employee_path %>

<h1><%= @employee.name %></h1>
<b>Contact: <%= @employee.contact %></b>
<p>Status: <%= @employee.status %></p>
<p>Salary: <%= @employee.salary %></p>
<hr/>
<%= render partial: 'skills/skill_green', collection: @employee.skills %>
<hr/>
<h3>Vacancies 100% match</h3>
<%= render partial: 'vacancies/vacancy', collection: @full %>
<h3>Parted</h3>
<%= render partial: 'vacancies/vacancy', collection: @parted %>