config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :employees, :vacancies do
    resources :skills
  end

  root 'welcome#index'

end

app/models/concerns/has_skills.rb
module HasSkills
  def self.included(base)
    base.class_eval do
      has_many :skill_links, as: :skillable
      has_many :skills, through: :skill_links

      accepts_nested_attributes_for :skill_links
    end
  end
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  include HasSkills

  validates :title, :salary, :contact, presence: true
  validates :contact, email: true

  # we can use this default scope, but default_scope can be sux
  # default_scope {order(salary: :desc)}

  scope :active, -> {where('expired > ?', Time.zone.now)}
  scope :arch, -> {where('expired < ?', Time.zone.now)}
end

app/controllers/api/v1/vacancies_controller.rb
class Api::V1::VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :update, :destroy]
  include Gotskills
  include Gotaliens

  respond_to :json

  def index
    @active = Vacancy.active.includes(:skills)
    @expired = Vacancy.arch.includes(:skills)
    @all = @active + @expired
    respond_with @all
  end

  def show
    got_skills @vacancy
    got_aliens @vacancy.skills, Employee.active.includes(:skills)
    respond_with @vacancy
  end

  def new
    @vacancy = Vacancy.new
    @skill = Skill.new
  end

  def create
    @vacancy= Vacancy.new(vacancy_params)
    @skill = Skill.new

    if @vacancy.skills.size == 0
      redirect_to :back, notice: 'Skills count cannot be zero'
    else
      respond_to do |format|
        if @vacancy.save
          format.html{ redirect_to @vacancy, notice: 'Vacancy created OK'}
          format.json{ render :show }
        else
          format.html{ render :new }
        end
      end
    end
  end

  def edit
    @vacancy = Vacancy.includes(:skills).find(params[:id])
    @skill = Skill.new
  end

  def update
    @vacancy.skill_links.build.build_skill

    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html{ redirect_to @vacancy, notice: 'Vacancy edited OK'}
      else
        format.html{ render :edit, notice: 'Vacancy not edited'}
      end
    end
  end

  private

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def vacancy_params
    params.require(:vacancy).permit(:title, :expired, :salary, :contact, skill_ids:[])
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :update, :destroy]
  include Gotskills
  include Gotaliens

  respond_to :html, :json

  def index
    @active = Vacancy.active.includes(:skills)
    @expired = Vacancy.arch.includes(:skills)
    @all = @active + @expired
    respond_with(@active)
  end

  def show
    got_skills @vacancy
    got_aliens @vacancy.skills, Employee.active.includes(:skills)
    respond_with(@vacancy)
    #render json: @vacancy
  end

  def new
    @vacancy = Vacancy.new
    @skill = Skill.new
  end

  def create
    @vacancy= Vacancy.new(vacancy_params)

    @skill = Skill.new

    if @vacancy.skills.size == 0
      redirect_to :back, notice: 'Skills count cannot be zero'
    else
      respond_to do |format|
        if @vacancy.save
          format.html{ redirect_to @vacancy, notice: 'Vacancy created OK'}
          format.json{ render :show }
        else
          format.html{ render :new }
        end
      end
    end
  end

  def edit
    @vacancy = Vacancy.includes(:skills).find(params[:id])
    @skill = Skill.new
  end

  def update
    @vacancy.skill_links.build.build_skill

    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html{ redirect_to @vacancy, notice: 'Vacancy edited OK'}
      else
        format.html{ render :edit, notice: 'Vacancy not edited'}
      end
    end
  end

  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html{ redirect_to vacancies_path, notice: 'Vacancy killed' }
    end
  end

  private

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  def vacancy_params
    params.require(:vacancy).permit(:title, :expired, :salary, :contact, skill_ids:[])
  end
end

app/views/vacancies/_form.html.erb
<%= form_for @vacancy do |f| %>
    <% if @vacancy.errors.any? %>
        <% content_for :footer do %>
        <div id="error_explanation">
          <h2><%= pluralize(@vacancy.errors.count, 'error')%> prohibited this emp from being saved</h2>
          <ul>
            <%= @vacancy.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, required: true, autofocus: true%>
    </div>
    <div class="field">
      <%= f.label :contact %>
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :salary %>
      <%= f.text_field :salary %>
    </div>
    <div class="field">
      <%= f.label :expired %>
      <%= f.datetime_select :expired, minute_step: 15 %>
    </div>
    <div class="field" id="allskills">
        <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name %>
    </div>

    <div class="actions">
      <%= f.submit 'OK'%>
    </div>
<% end %>

app/views/vacancies/_vacancy.html.erb
<div class="block">
  <h3><%= vacancy.title %> <small>Expired: <%= vacancy.expired ? vacancy.expired.to_formatted_s(:long) : vacancy.expired %></small></h3>
  <b>Salary:</b><i><%= vacancy.salary %></i>
  <br/>
  <% if vacancy.skills %>
  <small>
    <% vacancy.skills.each do |s|%>
        <%= s.name %>
    <% end %>
  </small>
  <% end %>

  <div class="buttons">
    <%= link_to 'show', vacancy %>
    <%= link_to 'edit', edit_vacancy_path(vacancy) %>
  </div>
</div>

app/views/vacancies/edit.html.erb
<% title 'Edit vacancy' %>
<% menu 'back to all', vacancies_path %>

<%= render 'form' %>

<div class="center">
  <%= link_to 'create new skill', new_skill_path, id: 'add_skill', remote: true %>
</div>

app/views/vacancies/index.html.erb
<% title 'Vacancies' %>
<% menu 'add new vacancy', new_vacancy_path %>

<h1>Active vacancies</h1>

<%= render partial: 'vacancy', collection: @active %>
<hr/>

<h3>Expired vacancies</h3>
<%= render partial: 'vacancy', collection: @expired %>

app/views/vacancies/new.html.erb
<% title 'New vacancy' %>
<% menu 'cancel', vacancies_path %>

<%= render 'form' %>

<div class="center">
  <%= link_to 'create new skill', new_skill_path, id: 'add_skill', remote: true %>
</div>

app/views/vacancies/show.html.erb
<% title @vacancy.title %>
<% menu 'edit', edit_vacancy_path %>

<h1><%= @vacancy.title %> <small>Expired: <%= @vacancy.expired.to_s(:long) %></small></h1>
<p>Salary: <%= @vacancy.salary %></p>
<p>Contact: <%= @vacancy.contact %></p>

<h3>Skills required</h3>
<%= render partial: 'skills/skill_green', collection: @vacancy.skills %>
<hr/>

<h3>Employees 100% match</h3>
<%= render partial: 'employees/employee', collection: @full %>
<hr/>

<h3>Parted</h3>
<%= render partial: 'employees/employee', collection: @parted %>